### ISSUE TITLE
Possibly image Your_First_Breadboard_Add_power_bb.png is incorrect

### ISSUE THREAD

**Issue by Michael-S** [readysetstem/readysetstem-projects#2]
I have one of the older Raspberry STEM kits.  For the image referenced, in order to get the light to turn on I had to swap the position of the wires connected to the GPIO ports.

It's entirely possible this is my own user error, I am a novice.  But I've disassembled and reassembled my Raspberry STEM kit twice and spent hours trying to get the bulb to light up any other way, with no result.

**Comment by brian-silverman** [comment]
Would you mind posting a picture of your setup?

Something to remember - the LED is unidirectional, as discussed in "YOUR FIRST CIRCUIT".  Is it possible the LED is connected backwards?

Also, you can send an image directly to support@readysetstem.com, if you'd prefer.

Thanks!

**Comment by Michael-S** [comment]
How did I miss that the LED is unidirectional?  That was it.  Thanks so much for your help!  I'll continue with the lessons with my daughter and I tonight.

**Comment by brian-silverman** [comment]
Great to hear it.  Good luck & enjoy!
